import * as vscode from 'vscode';
import { Mistral } from '@mistralai/mistralai';
import { dbStructure } from '../sqlite/RunQuery';
// Retrieve API Key from VS Code settings
const apiKey = vscode.workspace.getConfiguration('sqlQueryGenerator').get<string>('mistralApiKey') || "";

if (!apiKey) {
    vscode.window.showErrorMessage("Mistral API key is missing! Please add it in settings.json.");
}

// Initialize Mistral API client
const client = new Mistral({ apiKey });

/**
 * Function to create a VS Code Webview panel for user input and AI-generated SQL queries.
 */
export function openSQLQueryPanel() {
    const panel = vscode.window.createWebviewPanel(
        'sqlQueryGenerator',
        'SQL Query Generator',
        vscode.ViewColumn.One,
        { enableScripts: true }
    );

    panel.webview.html = getWebviewContent();
    panel.webview.onDidReceiveMessage(
        async (message) => {
            if (message.command === 'generateQuery') {
                const sqlQuery = await generateSQLQuery(message.text, dbStructure);
                panel.webview.postMessage({ command: 'displayQuery', query: sqlQuery });
            }
        },
        undefined,
        []
    );
}

/**
 * Function to send a natural language query to Mistral API and receive an SQL query response.
 * @param prompt - User input in plain English
 * @returns SQL query generated by the AI model
 */
async function generateSQLQuery(prompt: string, db: string): Promise<string> {
    try {
        console.log("Sending request to Mistral API...");

        const chatResponse = await client.chat.complete({
            model: "mistral-large-latest",
            messages: [{ role: "user", content: `For the database: ${db}, Generate an SQL query for: ${prompt}` }],
            temperature: 0.7
        });

        console.log("Mistral API Response:", chatResponse);

        // ✅ Ensure chatResponse and chatResponse.choices exist
        if (!chatResponse || !chatResponse.choices || chatResponse.choices.length === 0) {
            throw new Error("Invalid response from Mistral API: No choices found.");
        }

        let content = chatResponse.choices[0].message.content;

        // ✅ Handle the case where content is an array
        if (Array.isArray(content)) {
            content = content.map(chunk => chunk.toString()).join(" ");
        }

        return content as string;
    } catch (error: any) {
        console.error("Error generating SQL query:", error.message || error);
        return `Failed to generate SQL query: ${error.message || "Unknown error"}`;
    }
}

/**
 * Returns the HTML content for the Webview.
 */
function getWebviewContent(): string {
    return `
    <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; padding: 20px; }
                input, button { padding: 10px; margin-top: 10px; width: 100%; font-size: 16px; }
                button { background-color: #007acc; color: white; border: none; cursor: pointer; }
                button:hover { background-color: #005f99; }
                pre { background: #f4f4f4; padding: 15px; border-radius: 5px; white-space: pre-wrap; word-wrap: break-word; }
            </style>
        </head>
        <body>
            <h2>SQL Query Generator</h2>
            <input id="queryInput" type="text" placeholder="Enter your natural language query">
            <button onclick="sendQuery()">Generate SQL</button>
            <h3>Generated SQL Query:</h3>
            <pre id="sqlOutput">Waiting for input...</pre>

            <script>
                const vscode = acquireVsCodeApi();

                function sendQuery() {
                    const query = document.getElementById('queryInput').value;
                    vscode.postMessage({ command: 'generateQuery', text: query });
                }

                window.addEventListener('message', event => {
                    if (event.data.command === 'displayQuery') {
                        document.getElementById('sqlOutput').textContent = event.data.query;
                    }
                });
            </script>
        </body>
    </html>`;
}