CREATE TABLE USERS (
    id INT PRIMARY KEY,
    USERNAME varchar(50)
);

CREATE TABLE YUGAMI (
    peak INT PRIMARY KEY,
    USERNAME varchar(50)
);

CREATE TABLE MANGA   (
    awesomeSauce INT PRIMARY KEY,
    USERNAME varchar(50)
);